"""Strict models for the GraphRAG evidence package.

The package is what the LLM will be given in Gate 4 instead of raw data: four
clearly separated sections of evidence items, each item a claim with its
provenance. Nothing in it is generated by a model; every claim is produced by
deterministic code from graph, vector or policy results, and every one
resolves to real entity ids or a policy anchor.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from evidence.feature_assembler import Feature
from retrieval.case_retriever import PriorCaseRetrieval
from retrieval.policy_retriever import PolicyRetrieval

Section = Literal["trigger_and_baseline", "graph_evidence", "case_memory", "policy_context"]
SECTIONS: tuple[Section, ...] = (
    "trigger_and_baseline",
    "graph_evidence",
    "case_memory",
    "policy_context",
)

IndependenceGroup = Literal[
    "trigger_model",
    "customer_history",
    "temporal_sequence",
    "device_network",
    "region_network",
    "case_memory",
    "customer_response",
    "policy",
]

Strength = Literal["supporting", "contradicting", "neutral"]

#: ``graph`` is an installed structural query, ``graph_vector`` a TigerGraph
#: vector search, ``policy_document`` a retrieved policy or typology chunk.
SourceType = Literal["graph", "graph_vector", "policy_document"]

#: ``observed`` means the query completed and the claim states what it found.
#: The other three are never evidence of absence: a withheld, refused or
#: inapplicable section is unknown, and its item is always ``neutral``.
Availability = Literal["observed", "withheld", "refused", "not_applicable"]


class EvidenceItem(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    evidence_id: str
    section: Section
    claim: str
    source_type: SourceType
    #: What an answer's evidence ``ref`` will cite: ``query:<name>`` or
    #: ``policy:<anchor>`` / ``pattern:<anchor>``.
    ref: str
    query_name: str | None = None
    document_ref: str | None = None
    query_bundle_version: str
    parameters: dict[str, Any] = Field(default_factory=dict)
    entity_ids: list[str]
    value: Any = None
    feature_names: list[str] = Field(default_factory=list)
    anchor_time: str
    #: Latest source timestamp the claim rests on; None for an undated document.
    data_max_time: str | None
    leakage_check_passed: bool
    independence_group: IndependenceGroup
    strength: Strength
    availability: Availability = "observed"
    retrieval: dict[str, Any] | None = None
    path_segments: list[dict[str, Any]] | None = None
    #: The graph call behind the claim. Excluded from the content hash, since a
    #: rerun gets new trace ids for identical content.
    trace_id: str = ""
    content_hash: str
    previous_hash: str


class CallSummary(BaseModel):
    model_config = ConfigDict(extra="forbid")

    trace_id: str
    adapter: str
    tool: str
    query_name: str
    duration_ms: float
    ok: bool
    result_bytes: int
    error_class: str = ""


class PackageMetadata(BaseModel):
    model_config = ConfigDict(extra="forbid")

    port_mode: str
    primary_adapter: str
    fallback_occurred: bool
    fallback_events: list[dict[str, Any]] = Field(default_factory=list)
    adapters_used: dict[str, int]
    mcp_trace_ids: list[str]
    graph_call_count: int
    graph_call_budget: int
    calls: list[CallSummary]
    query_versions: dict[str, str]
    query_bundle_version: str
    created_at: str
    anchor_time: str
    review_time: str
    data_max_time: str
    withheld_or_unavailable: dict[str, list[str]]
    caps: dict[str, int]
    truncated: dict[str, bool] = Field(default_factory=dict)


class EvidencePackage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    package_id: str
    case_id: str
    trigger: dict[str, Any]
    anchor_time: str
    data_max_time: str
    leakage_check_passed: bool
    sections: dict[Section, list[EvidenceItem]]
    features: dict[str, Feature]
    prior_case_retrieval: PriorCaseRetrieval
    policy_retrieval: PolicyRetrieval
    #: Every id any graph or vector result returned: what a claim may cite.
    observed_entity_ids: list[str]
    ledger_final_hash: str
    metadata: PackageMetadata

    def items(self) -> list[EvidenceItem]:
        return [item for section in SECTIONS for item in self.sections.get(section, [])]

    def item(self, evidence_id: str) -> EvidenceItem | None:
        return next((item for item in self.items() if item.evidence_id == evidence_id), None)

    def counts(self) -> dict[str, Any]:
        items = self.items()
        return {
            "sections": {section: len(self.sections.get(section, [])) for section in SECTIONS},
            "strength": {
                strength: sum(1 for item in items if item.strength == strength)
                for strength in ("supporting", "contradicting", "neutral")
            },
            "availability": {
                state: sum(1 for item in items if item.availability == state)
                for state in ("observed", "withheld", "refused", "not_applicable")
            },
            "items": len(items),
            "prior_cases": len(self.prior_case_retrieval.cases),
            "policy_chunks": len(self.policy_retrieval.chunks),
        }
